name: photography_application
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  equatable: ^2.0.7
  google_fonts: ^6.2.1
  flutter_screenutil: ^5.9.3
  fluro: ^2.0.5
  infinite_scroll_pagination: ^4.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  firebase_core: ^3.6.0
  firebase_storage: ^12.3.3
  path: ^1.8.3
  cloud_firestore: ^5.4.4
  firebase_core_web: ^2.17.5
  firebase_storage_web: ^3.10.2
  js: ^0.6.7
  firebase_auth: ^5.3.1
  firebase_analytics: ^11.3.3
  provider: ^6.1.2
  flutter_bloc: ^8.1.6
  cached_network_image: ^3.3.1
  intl: ^0.19.0
  timeago: ^3.6.0
  email_validator: ^3.0.0
  font_awesome_flutter: ^10.8.0
  get: ^4.7.2
  google_sign_in: ^6.3.0
  image_picker: ^1.1.2
  file_picker: ^8.0.7
  smooth_page_indicator: ^1.2.1
  firebase_messaging: ^15.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.6
  hive_generator: ^2.0.1

flutter:
  assets:
    - assets/images/
  uses-material-design: true