// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6sS5zPUFkiTlAw8qwou8kBgGVsRd5ccA',
    appId: '1:686318528774:web:afba923deff60f17671687',
    messagingSenderId: '686318528774',
    projectId: 'photography-application-17813',
    authDomain: 'photography-application-17813.firebaseapp.com',
    storageBucket: 'photography-application-17813.firebasestorage.app',
    measurementId: 'G-PW1QXTTF4B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8OEwIrceHCCPXlYHhFFe82HzgcUTIQmU',
    appId: '1:686318528774:android:103a646fdb01e60c671687',
    messagingSenderId: '686318528774',
    projectId: 'photography-application-17813',
    storageBucket: 'photography-application-17813.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfVkpJKkEaoFWVOtWGQicbbkK0OQbmeRY',
    appId: '1:686318528774:ios:012cdebe000ac688671687',
    messagingSenderId: '686318528774',
    projectId: 'photography-application-17813',
    storageBucket: 'photography-application-17813.firebasestorage.app',
    androidClientId: '686318528774-3lbtq54mjlhnfg1845oe27ffra5krjpk.apps.googleusercontent.com',
    iosClientId: '686318528774-aehjeicteg5a10n5dgjp9t911sq3fooo.apps.googleusercontent.com',
    iosBundleId: 'com.example.photographyApplication',
  );
}
